### ISSUE TITLE
As a developer I want a basic unit testing for the proto definitions for sanity checking

### ISSUE THREAD

**Issue by nshCore** [catalyst-network/Protocol#7]
We eventually want some type of unit testing for protobuffs. Protobuffs doesnt have native UT functionality so we would need to generate them to a language like c#/js and write UT in for them in there.

**Comment by monsieurleberre** [comment]
for reference
https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md

**Comment by monsieurleberre** [comment]
Closing this as we now 2 steps which should overall ensure things don't go crazy:
- the Azure pipeline triggered by this project attempts to generate c# files, which ensure the syntax is correct
- the Azure pipeline for the SDK projects compiles the proto and has a test suite which can be enriched as we progress
